-- 为现有业务表补充 PostgreSQL 元数据说明。
-- 本迁移只写 COMMENT，不修改表结构、约束、索引或业务数据。

COMMENT ON TABLE public.users IS '用户主表，保存控制台账户状态、加密身份信息和登录审计摘要。';
COMMENT ON COLUMN public.users.id IS '用户全局唯一标识。';
COMMENT ON COLUMN public.users.display_name IS '用户在控制台展示的名称。';
COMMENT ON COLUMN public.users.email_ciphertext IS '使用 AES-256-GCM 加密保存的邮箱密文，禁止直接查询展示或写入日志。';
COMMENT ON COLUMN public.users.email_lookup_hash IS '规范化邮箱的 HMAC-SHA256 查询摘要，用于唯一性校验和登录查找，不可反推出邮箱。';
COMMENT ON COLUMN public.users.email_key_version IS '邮箱密文及查询摘要使用的密钥版本，用于安全轮换。';
COMMENT ON COLUMN public.users.password_hash IS 'Argon2id 密码摘要，只用于服务端密码校验。';
COMMENT ON COLUMN public.users.status IS '用户状态：active、pending、suspended、locked 或 deleted。';
COMMENT ON COLUMN public.users.email_verified_at IS '邮箱验证完成时间；尚未验证时为空。';
COMMENT ON COLUMN public.users.avatar_url IS '用户头像文件或对象存储地址。';
COMMENT ON COLUMN public.users.registered_ip IS '注册时客户端 IP，用于安全审计和反滥用。';
COMMENT ON COLUMN public.users.registered_user_agent_hash IS '注册时 User-Agent 的不可逆摘要，避免保存完整设备指纹。';
COMMENT ON COLUMN public.users.last_login_at IS '最近一次成功登录时间。';
COMMENT ON COLUMN public.users.created_at IS '用户记录创建时间。';
COMMENT ON COLUMN public.users.updated_at IS '用户记录最后更新时间。';
COMMENT ON COLUMN public.users.deleted_at IS '软删除时间；为空表示用户记录未删除。';

COMMENT ON TABLE public.user_roles IS '用户角色关联表，为控制台和管理接口提供后端权限判定依据。';
COMMENT ON COLUMN public.user_roles.user_id IS '被授予角色的用户标识。';
COMMENT ON COLUMN public.user_roles.role_code IS '角色代码：user、operator 或 admin。';
COMMENT ON COLUMN public.user_roles.granted_by IS '执行授权的管理员用户标识；系统初始化授权时可为空。';
COMMENT ON COLUMN public.user_roles.granted_at IS '角色授予时间。';

COMMENT ON TABLE public.api_keys IS '用户 API Key 配置表，保存摘要、状态和调用限制，不保存可回显的完整密钥。';
COMMENT ON COLUMN public.api_keys.id IS 'API Key 记录全局唯一标识。';
COMMENT ON COLUMN public.api_keys.user_id IS 'API Key 所属用户标识，管理查询必须按该字段隔离用户资源。';
COMMENT ON COLUMN public.api_keys.name IS '用户为 API Key 设置的可读名称。';
COMMENT ON COLUMN public.api_keys.key_prefix IS '可公开展示的 Key 前缀，用于识别 Key 类型和版本。';
COMMENT ON COLUMN public.api_keys.key_suffix IS '可公开展示的 Key 末尾字符，用于区分多个 Key。';
COMMENT ON COLUMN public.api_keys.key_hash IS '完整 API Key 的版本化 HMAC-SHA256 摘要，用于常量时间鉴权比对。';
COMMENT ON COLUMN public.api_keys.status IS 'Key 状态：active、disabled、expired 或 revoked。';
COMMENT ON COLUMN public.api_keys.default_group_id IS '未显式指定分组时使用的默认计费与路由分组标识。';
COMMENT ON COLUMN public.api_keys.allowed_model_ids IS '允许调用的模型 UUID JSON 数组；空数组表示不额外限制模型。';
COMMENT ON COLUMN public.api_keys.allowed_group_ids IS '允许使用的分组 UUID JSON 数组；空数组表示不额外限制分组。';
COMMENT ON COLUMN public.api_keys.ip_allowlist IS '允许来源 IP 或 CIDR JSON 数组；空数组表示不启用 IP 白名单。';
COMMENT ON COLUMN public.api_keys.rpm_limit IS '每分钟最大请求数 RPM；为空表示不设置 Key 级限制。';
COMMENT ON COLUMN public.api_keys.tpm_limit IS '每分钟最大 Token 数 TPM；为空表示不设置 Key 级限制。';
COMMENT ON COLUMN public.api_keys.concurrency_limit IS '该 Key 允许的最大并发请求数；为空表示不设置 Key 级限制。';
COMMENT ON COLUMN public.api_keys.credit_limit IS '该 Key 可累计消费的平台额度上限；为空表示不设置 Key 级上限。';
COMMENT ON COLUMN public.api_keys.expires_at IS 'Key 到期时间；为空表示没有预设到期时间。';
COMMENT ON COLUMN public.api_keys.last_used_at IS '最近一次成功通过鉴权并使用该 Key 的时间。';
COMMENT ON COLUMN public.api_keys.created_at IS 'Key 创建时间。';
COMMENT ON COLUMN public.api_keys.updated_at IS 'Key 配置或状态最后更新时间。';
COMMENT ON COLUMN public.api_keys.revoked_at IS 'Key 被永久撤销的时间；未撤销时为空。';
COMMENT ON COLUMN public.api_keys.key_hash_version IS '生成 key_hash 时使用的 HMAC 密钥版本。';
COMMENT ON COLUMN public.api_keys.version IS '乐观锁版本号，防止并发管理请求相互覆盖。';
COMMENT ON COLUMN public.api_keys.status_changed_at IS 'Key 状态最近一次发生变化的时间。';

COMMENT ON TABLE public.ai_models IS '平台公开模型目录和用户售价配置表。';
COMMENT ON COLUMN public.ai_models.id IS '模型配置全局唯一标识。';
COMMENT ON COLUMN public.ai_models.public_name IS '对外兼容 OpenAI 协议的稳定模型名称。';
COMMENT ON COLUMN public.ai_models.display_name IS '管理端和公开模型目录显示的可读名称。';
COMMENT ON COLUMN public.ai_models.provider IS '模型归属提供商标识，例如 openai 或 anthropic。';
COMMENT ON COLUMN public.ai_models.capability_type IS '能力类型：text、image、audio、video、embedding 或 multimodal。';
COMMENT ON COLUMN public.ai_models.input_modalities IS '支持的输入模态 JSON 数组。';
COMMENT ON COLUMN public.ai_models.output_modalities IS '支持的输出模态 JSON 数组。';
COMMENT ON COLUMN public.ai_models.context_window IS '最大上下文 Token 数；上游未提供明确限制时为空。';
COMMENT ON COLUMN public.ai_models.max_output_tokens IS '单次响应允许的最大输出 Token 数；上游未提供明确限制时为空。';
COMMENT ON COLUMN public.ai_models.supports_streaming IS '是否支持 SSE 流式响应。';
COMMENT ON COLUMN public.ai_models.supports_tools IS '是否支持工具或函数调用。';
COMMENT ON COLUMN public.ai_models.supports_structured_output IS '是否支持 JSON Schema 等结构化输出。';
COMMENT ON COLUMN public.ai_models.input_price IS '输入 Token 对用户的基础售价，计价单位由 price_unit 指定。';
COMMENT ON COLUMN public.ai_models.output_price IS '输出 Token 对用户的基础售价，计价单位由 price_unit 指定。';
COMMENT ON COLUMN public.ai_models.cached_input_price IS '命中缓存的输入 Token 基础售价，计价单位由 price_unit 指定。';
COMMENT ON COLUMN public.ai_models.price_unit IS '价格计量单位，例如 million_tokens 表示每百万 Token。';
COMMENT ON COLUMN public.ai_models.public_visible IS '是否在普通用户可访问的公开模型目录中展示。';
COMMENT ON COLUMN public.ai_models.status IS '模型状态：active、disabled 或 maintenance。';
COMMENT ON COLUMN public.ai_models.metadata IS '模型非敏感扩展元数据 JSON。';
COMMENT ON COLUMN public.ai_models.created_at IS '模型配置创建时间。';
COMMENT ON COLUMN public.ai_models.updated_at IS '模型配置最后更新时间。';
COMMENT ON COLUMN public.ai_models.version IS '乐观锁版本号，防止并发修改价格或能力配置时相互覆盖。';

COMMENT ON TABLE public.channels IS '上游 AI 渠道配置表，凭证加密保存且只允许网关在请求前按需解密。';
COMMENT ON COLUMN public.channels.id IS '上游渠道全局唯一标识。';
COMMENT ON COLUMN public.channels.name IS '管理端显示且全局唯一的渠道名称。';
COMMENT ON COLUMN public.channels.provider_type IS '渠道协议或提供商类型，例如 openai 或 azure_openai。';
COMMENT ON COLUMN public.channels.base_url IS '上游 API 基础地址，不应包含密钥或其他凭证参数。';
COMMENT ON COLUMN public.channels.encrypted_credential IS '使用独立 AAD 域进行 AES-256-GCM 加密的渠道凭证密文，禁止回显或记录日志。';
COMMENT ON COLUMN public.channels.credential_key_version IS '加密渠道凭证所使用的密钥版本，用于安全轮换和向后解密。';
COMMENT ON COLUMN public.channels.proxy_url IS '访问该渠道时使用的代理地址；不使用代理时为空。';
COMMENT ON COLUMN public.channels.status IS '渠道状态：active、disabled、degraded 或 circuit_open。';
COMMENT ON COLUMN public.channels.timeout_ms IS '单次上游请求超时时间，单位毫秒。';
COMMENT ON COLUMN public.channels.concurrency_limit IS '渠道允许的最大并发请求数；为空表示不设置渠道级限制。';
COMMENT ON COLUMN public.channels.priority IS '渠道默认路由优先级，数值越小越优先。';
COMMENT ON COLUMN public.channels.weight IS '同优先级渠道参与加权随机路由时的默认权重。';
COMMENT ON COLUMN public.channels.consecutive_failures IS '连续上游失败次数，用于熔断状态判断。';
COMMENT ON COLUMN public.channels.circuit_open_until IS '熔断保持到该时间，在此之前不得继续选择该渠道。';
COMMENT ON COLUMN public.channels.last_error_summary IS '最近一次上游错误的脱敏摘要，禁止包含请求正文或凭证。';
COMMENT ON COLUMN public.channels.metadata IS '渠道非敏感扩展元数据 JSON。';
COMMENT ON COLUMN public.channels.created_at IS '渠道配置创建时间。';
COMMENT ON COLUMN public.channels.updated_at IS '渠道配置最后更新时间。';
COMMENT ON COLUMN public.channels.credential_fingerprint IS '凭证不可逆短指纹，仅用于管理员确认轮换结果，不具备鉴权能力。';
COMMENT ON COLUMN public.channels.credential_updated_at IS '最近一次创建或轮换渠道凭证的时间。';
COMMENT ON COLUMN public.channels.version IS '乐观锁版本号，防止并发配置或凭证轮换相互覆盖。';

COMMENT ON TABLE public.channel_models IS '上游渠道与平台模型的映射、成本价和路由参数配置表。';
COMMENT ON COLUMN public.channel_models.id IS '渠道模型映射全局唯一标识。';
COMMENT ON COLUMN public.channel_models.channel_id IS '所属上游渠道标识。';
COMMENT ON COLUMN public.channel_models.model_id IS '对应平台模型标识。';
COMMENT ON COLUMN public.channel_models.upstream_model IS '发送给上游渠道的真实模型名称。';
COMMENT ON COLUMN public.channel_models.priority IS '该渠道内模型映射的路由优先级，数值越小越优先。';
COMMENT ON COLUMN public.channel_models.weight IS '同优先级映射参与加权随机路由时的权重。';
COMMENT ON COLUMN public.channel_models.cost_input_price IS '上游输入 Token 成本价，计价单位与平台模型 price_unit 保持一致。';
COMMENT ON COLUMN public.channel_models.cost_output_price IS '上游输出 Token 成本价，计价单位与平台模型 price_unit 保持一致。';
COMMENT ON COLUMN public.channel_models.status IS '映射状态：active 或 disabled。';
COMMENT ON COLUMN public.channel_models.config IS '非敏感的渠道模型扩展配置 JSON，禁止嵌入 API Key、Token 或密码。';
COMMENT ON COLUMN public.channel_models.created_at IS '映射创建时间。';
COMMENT ON COLUMN public.channel_models.updated_at IS '映射最后更新时间。';
COMMENT ON COLUMN public.channel_models.version IS '乐观锁版本号，防止并发修改成本价或路由参数时相互覆盖。';

COMMENT ON TABLE public.routing_groups IS '用户计费倍率和模型路由分组配置表。';
COMMENT ON COLUMN public.routing_groups.id IS '计费与路由分组全局唯一标识。';
COMMENT ON COLUMN public.routing_groups.code IS '稳定且全局唯一的分组代码，用于配置和策略引用。';
COMMENT ON COLUMN public.routing_groups.name IS '管理端展示的分组名称。';
COMMENT ON COLUMN public.routing_groups.description IS '分组用途和适用范围说明。';
COMMENT ON COLUMN public.routing_groups.price_multiplier IS '用户最终价格倍率，实际价格等于模型基础售价乘以该值。';
COMMENT ON COLUMN public.routing_groups.audience IS '可见范围：all、assigned 或 internal。';
COMMENT ON COLUMN public.routing_groups.status IS '分组状态：active、disabled 或 degraded。';
COMMENT ON COLUMN public.routing_groups.created_at IS '分组创建时间。';
COMMENT ON COLUMN public.routing_groups.updated_at IS '分组最后更新时间。';
COMMENT ON COLUMN public.routing_groups.version IS '乐观锁版本号，防止并发修改倍率或状态时相互覆盖。';

COMMENT ON TABLE public.group_routes IS '分组、平台模型与渠道模型映射之间的运行时路由规则表。';
COMMENT ON COLUMN public.group_routes.id IS '分组路由规则全局唯一标识。';
COMMENT ON COLUMN public.group_routes.group_id IS '路由规则所属计费分组标识。';
COMMENT ON COLUMN public.group_routes.model_id IS '客户端请求的平台模型标识。';
COMMENT ON COLUMN public.group_routes.channel_model_id IS '被选择的渠道模型映射标识。';
COMMENT ON COLUMN public.group_routes.priority IS '路由优先级，数值越小越先进入候选集合。';
COMMENT ON COLUMN public.group_routes.weight IS '同优先级路由规则参与加权随机选择时的权重。';
COMMENT ON COLUMN public.group_routes.retryable IS '上游失败后是否允许切换到其他符合条件的路由规则重试。';
COMMENT ON COLUMN public.group_routes.status IS '路由规则状态：active 或 disabled。';
COMMENT ON COLUMN public.group_routes.created_at IS '路由规则创建时间。';
COMMENT ON COLUMN public.group_routes.updated_at IS '路由规则最后更新时间。';
COMMENT ON COLUMN public.group_routes.version IS '乐观锁版本号，防止并发修改优先级、权重或状态时相互覆盖。';

COMMENT ON TABLE public.wallet_accounts IS '用户钱包余额快照表，所有余额写入必须由 billing 服务在行锁事务内完成。';
COMMENT ON COLUMN public.wallet_accounts.user_id IS '钱包所属用户标识，同时也是钱包账户主键。';
COMMENT ON COLUMN public.wallet_accounts.permanent_credits IS '永久有效的平台额度余额，不参与自动过期。';
COMMENT ON COLUMN public.wallet_accounts.expiring_credits IS '带有效期的平台额度汇总余额，由到期任务按明细扣减。';
COMMENT ON COLUMN public.wallet_accounts.frozen_credits IS '已为在途请求冻结、暂不可再次消费的平台额度。';
COMMENT ON COLUMN public.wallet_accounts.version IS '钱包乐观锁版本号，每次余额变更后递增。';
COMMENT ON COLUMN public.wallet_accounts.updated_at IS '钱包余额快照最后更新时间。';

COMMENT ON TABLE public.billing_ledger IS '不可变资金账本，是余额变化、冻结、结算、释放和退款的审计真相源。';
COMMENT ON COLUMN public.billing_ledger.id IS '账本流水全局唯一标识。';
COMMENT ON COLUMN public.billing_ledger.user_id IS '账本所属用户标识，幂等键也按用户维度隔离。';
COMMENT ON COLUMN public.billing_ledger.request_id IS '贯穿网关、计费和调用日志的请求标识。';
COMMENT ON COLUMN public.billing_ledger.entry_type IS '流水类型：recharge、grant、reserve、settle、release、refund、expire 或 adjustment。';
COMMENT ON COLUMN public.billing_ledger.amount IS '本次永久、有效期和冻结三个分桶变化量之和，可正、可负或为零。';
COMMENT ON COLUMN public.billing_ledger.balance_after IS '操作后总资产快照，等于永久额度、有效期额度与冻结额度之和。';
COMMENT ON COLUMN public.billing_ledger.idempotency_key IS '用户维度唯一的幂等键，用于避免重复入账或扣费。';
COMMENT ON COLUMN public.billing_ledger.source_type IS '业务来源类型，例如 order、request、admin 或 subscription。';
COMMENT ON COLUMN public.billing_ledger.source_id IS '业务来源记录标识，便于审计追溯。';
COMMENT ON COLUMN public.billing_ledger.expires_at IS '本笔额度的到期时间；永久额度或无到期语义时为空。';
COMMENT ON COLUMN public.billing_ledger.metadata IS '非敏感业务元数据 JSON，禁止保存密码、Token、密钥或完整凭证。';
COMMENT ON COLUMN public.billing_ledger.created_at IS '账本流水创建时间；账本只允许追加，创建后不可修改或删除。';
COMMENT ON COLUMN public.billing_ledger.api_key_id IS '关联 API Key 标识；非 API Key 消费类流水可为空。';
COMMENT ON COLUMN public.billing_ledger.reservation_id IS '关联冻结单标识；充值、赠送等非请求流水可为空。';
COMMENT ON COLUMN public.billing_ledger.permanent_delta IS '本次永久额度变化量。';
COMMENT ON COLUMN public.billing_ledger.expiring_delta IS '本次有效期额度变化量。';
COMMENT ON COLUMN public.billing_ledger.frozen_delta IS '本次冻结额度变化量。';
COMMENT ON COLUMN public.billing_ledger.permanent_after IS '操作后的永久额度余额。';
COMMENT ON COLUMN public.billing_ledger.expiring_after IS '操作后的有效期额度余额。';
COMMENT ON COLUMN public.billing_ledger.frozen_after IS '操作后的冻结额度余额。';
COMMENT ON COLUMN public.billing_ledger.available_after IS '操作后的可用余额，等于永久额度与有效期额度之和。';
COMMENT ON COLUMN public.billing_ledger.wallet_version_after IS '生成本流水后对应的钱包版本号。';

COMMENT ON TABLE public.wallet_reservations IS '单次 AI 请求的预冻结、实际结算、释放和累计退款状态表。';
COMMENT ON COLUMN public.wallet_reservations.id IS '冻结单全局唯一标识。';
COMMENT ON COLUMN public.wallet_reservations.user_id IS '冻结单所属用户标识。';
COMMENT ON COLUMN public.wallet_reservations.api_key_id IS '发起请求的 API Key 标识；系统内部请求可为空。';
COMMENT ON COLUMN public.wallet_reservations.request_id IS '关联 AI 调用的请求标识，同一用户内唯一。';
COMMENT ON COLUMN public.wallet_reservations.idempotency_key IS '创建冻结单的用户维度幂等键。';
COMMENT ON COLUMN public.wallet_reservations.status IS '冻结单状态：reserved、settled 或 released。';
COMMENT ON COLUMN public.wallet_reservations.reserved_amount IS '请求开始前预冻结的平台额度总额。';
COMMENT ON COLUMN public.wallet_reservations.reserved_permanent IS '预冻结金额中来自永久额度的部分。';
COMMENT ON COLUMN public.wallet_reservations.reserved_expiring IS '预冻结金额中来自有效期额度的部分。';
COMMENT ON COLUMN public.wallet_reservations.settled_amount IS '请求完成后按实际用量确认的累计结算额度。';
COMMENT ON COLUMN public.wallet_reservations.settled_permanent IS '实际结算中消耗永久额度的部分。';
COMMENT ON COLUMN public.wallet_reservations.settled_expiring IS '实际结算中消耗有效期额度的部分。';
COMMENT ON COLUMN public.wallet_reservations.refunded_amount IS '已针对该冻结单完成的累计退款额度。';
COMMENT ON COLUMN public.wallet_reservations.refunded_permanent IS '累计退款中退回永久额度的部分。';
COMMENT ON COLUMN public.wallet_reservations.refunded_expiring IS '累计退款中退回有效期额度的部分。';
COMMENT ON COLUMN public.wallet_reservations.settlement_idempotency_key IS '结算操作的用户维度幂等键；尚未结算时为空。';
COMMENT ON COLUMN public.wallet_reservations.release_idempotency_key IS '释放冻结操作的用户维度幂等键；尚未释放时为空。';
COMMENT ON COLUMN public.wallet_reservations.created_at IS '冻结单创建时间。';
COMMENT ON COLUMN public.wallet_reservations.settled_at IS '完成结算的时间；未结算时为空。';
COMMENT ON COLUMN public.wallet_reservations.released_at IS '未消费冻结额度被释放的时间；未释放时为空。';
COMMENT ON COLUMN public.wallet_reservations.updated_at IS '冻结单最后更新时间。';
COMMENT ON COLUMN public.wallet_reservations.version IS '冻结单乐观锁版本号，防止并发结算、释放或退款覆盖。';

COMMENT ON TABLE public.billing_refunds IS '每一次部分或全额退款的幂等明细表。';
COMMENT ON COLUMN public.billing_refunds.id IS '退款记录全局唯一标识。';
COMMENT ON COLUMN public.billing_refunds.user_id IS '退款所属用户标识。';
COMMENT ON COLUMN public.billing_refunds.reservation_id IS '被退款的原冻结单标识。';
COMMENT ON COLUMN public.billing_refunds.idempotency_key IS '用户维度唯一的退款幂等键。';
COMMENT ON COLUMN public.billing_refunds.amount IS '本次退款的平台额度总额。';
COMMENT ON COLUMN public.billing_refunds.permanent_amount IS '本次退回永久额度的金额。';
COMMENT ON COLUMN public.billing_refunds.expiring_amount IS '本次退回有效期额度的金额。';
COMMENT ON COLUMN public.billing_refunds.cumulative_amount IS '本次退款完成后该冻结单的累计退款总额。';
COMMENT ON COLUMN public.billing_refunds.refundable_after IS '本次退款完成后该冻结单仍可退款的额度。';
COMMENT ON COLUMN public.billing_refunds.reason IS '退款原因说明，不得包含密码、Token、密钥等敏感信息。';
COMMENT ON COLUMN public.billing_refunds.created_at IS '退款记录创建时间。';

COMMENT ON TABLE public.plans IS '商业套餐定义表，保存售价、计费周期、包含额度和权益配置。';
COMMENT ON COLUMN public.plans.id IS '套餐全局唯一标识。';
COMMENT ON COLUMN public.plans.code IS '稳定且全局唯一的套餐代码。';
COMMENT ON COLUMN public.plans.name IS '用户可见的套餐名称。';
COMMENT ON COLUMN public.plans.billing_cycle IS '计费周期：monthly、quarterly、yearly 或 one_time。';
COMMENT ON COLUMN public.plans.price IS '套餐销售金额，币种由订单 currency 确定。';
COMMENT ON COLUMN public.plans.included_credits IS '购买或续费套餐后包含的平台额度。';
COMMENT ON COLUMN public.plans.concurrency_limit IS '套餐提供的并发请求上限；为空表示不由套餐限制。';
COMMENT ON COLUMN public.plans.entitlements IS '套餐权益配置 JSON，例如模型或功能访问范围。';
COMMENT ON COLUMN public.plans.status IS '套餐状态：draft、active 或 archived。';
COMMENT ON COLUMN public.plans.created_at IS '套餐创建时间。';
COMMENT ON COLUMN public.plans.updated_at IS '套餐最后更新时间。';

COMMENT ON TABLE public.subscriptions IS '用户套餐订阅实例表，记录订阅周期、状态和自动续费设置。';
COMMENT ON COLUMN public.subscriptions.id IS '订阅全局唯一标识。';
COMMENT ON COLUMN public.subscriptions.user_id IS '订阅所属用户标识。';
COMMENT ON COLUMN public.subscriptions.plan_id IS '订阅对应的套餐标识。';
COMMENT ON COLUMN public.subscriptions.status IS '订阅状态：pending、active、expired、cancelled 或 refunded。';
COMMENT ON COLUMN public.subscriptions.starts_at IS '订阅权益生效时间。';
COMMENT ON COLUMN public.subscriptions.expires_at IS '订阅权益到期时间，必须晚于 starts_at。';
COMMENT ON COLUMN public.subscriptions.auto_renew IS '是否在到期前自动创建续费流程。';
COMMENT ON COLUMN public.subscriptions.cancelled_at IS '订阅取消时间；未取消时为空。';
COMMENT ON COLUMN public.subscriptions.created_at IS '订阅记录创建时间。';
COMMENT ON COLUMN public.subscriptions.updated_at IS '订阅记录最后更新时间。';

COMMENT ON TABLE public.orders IS '充值和订阅购买订单表，记录支付状态、金额和支付渠道关联信息。';
COMMENT ON COLUMN public.orders.id IS '订单全局唯一标识。';
COMMENT ON COLUMN public.orders.user_id IS '订单所属用户标识。';
COMMENT ON COLUMN public.orders.order_no IS '面向用户和客服的全局唯一订单号。';
COMMENT ON COLUMN public.orders.order_type IS '订单类型：recharge 或 subscription。';
COMMENT ON COLUMN public.orders.amount IS '订单应付金额。';
COMMENT ON COLUMN public.orders.currency IS '订单币种代码，默认 CNY。';
COMMENT ON COLUMN public.orders.status IS '订单状态：pending、paid、failed、cancelled 或 refunded。';
COMMENT ON COLUMN public.orders.payment_provider IS '支付渠道标识，例如 alipay、wechat 或 stripe。';
COMMENT ON COLUMN public.orders.provider_order_id IS '支付渠道返回的订单或交易标识。';
COMMENT ON COLUMN public.orders.idempotency_key IS '创建订单的全局唯一幂等键，防止重复下单。';
COMMENT ON COLUMN public.orders.paid_at IS '订单支付成功时间；未支付时为空。';
COMMENT ON COLUMN public.orders.closed_at IS '订单关闭或终态完成时间。';
COMMENT ON COLUMN public.orders.metadata IS '订单非敏感扩展元数据 JSON。';
COMMENT ON COLUMN public.orders.created_at IS '订单创建时间。';
COMMENT ON COLUMN public.orders.updated_at IS '订单最后更新时间。';

COMMENT ON TABLE public.request_logs IS '按月可扩展分区的 AI 调用明细表，记录路由、用量、计费和脱敏错误信息。';
COMMENT ON COLUMN public.request_logs.id IS '调用日志记录标识，与 created_at 共同组成分区主键。';
COMMENT ON COLUMN public.request_logs.request_id IS '贯穿客户端、网关、计费和上游调用的请求标识。';
COMMENT ON COLUMN public.request_logs.user_id IS '发起调用的用户标识。';
COMMENT ON COLUMN public.request_logs.api_key_id IS '发起调用的 API Key 标识。';
COMMENT ON COLUMN public.request_logs.model_id IS '客户端请求的平台模型标识。';
COMMENT ON COLUMN public.request_logs.channel_id IS '最终实际调用的上游渠道标识。';
COMMENT ON COLUMN public.request_logs.group_id IS '本次调用采用的计费与路由分组标识。';
COMMENT ON COLUMN public.request_logs.public_model IS '客户端请求中使用的平台公开模型名。';
COMMENT ON COLUMN public.request_logs.upstream_model IS '最终发送给上游的真实模型名。';
COMMENT ON COLUMN public.request_logs.started_at IS '平台开始处理请求的时间。';
COMMENT ON COLUMN public.request_logs.completed_at IS '请求完成或失败终止的时间。';
COMMENT ON COLUMN public.request_logs.duration_ms IS '平台处理请求总耗时，单位毫秒。';
COMMENT ON COLUMN public.request_logs.status_code IS '最终返回给客户端的 HTTP 状态码。';
COMMENT ON COLUMN public.request_logs.platform_error_code IS '平台归一化错误码；成功请求时为空。';
COMMENT ON COLUMN public.request_logs.input_tokens IS '上游确认的输入 Token 数。';
COMMENT ON COLUMN public.request_logs.output_tokens IS '上游确认的输出 Token 数。';
COMMENT ON COLUMN public.request_logs.cached_tokens IS '输入 Token 中命中缓存的数量。';
COMMENT ON COLUMN public.request_logs.billed_amount IS '本次调用最终结算的平台额度。';
COMMENT ON COLUMN public.request_logs.price_multiplier IS '本次调用实际采用的分组价格倍率快照。';
COMMENT ON COLUMN public.request_logs.streaming IS '本次调用是否使用 SSE 流式响应。';
COMMENT ON COLUMN public.request_logs.retry_count IS '发生可重试上游错误后实际执行的重试次数。';
COMMENT ON COLUMN public.request_logs.client_ip IS '客户端来源 IP，用于安全审计、限流和反滥用。';
COMMENT ON COLUMN public.request_logs.user_agent_hash IS '客户端 User-Agent 的不可逆摘要，避免保存完整设备指纹。';
COMMENT ON COLUMN public.request_logs.upstream_error_summary IS '上游错误的脱敏摘要，禁止包含请求正文、Token 或渠道凭证。';
COMMENT ON COLUMN public.request_logs.route_switch_reason IS '切换渠道或模型路由的归一化原因。';
COMMENT ON COLUMN public.request_logs.metadata IS '调用非敏感扩展元数据 JSON。';
COMMENT ON COLUMN public.request_logs.created_at IS '调用日志写入时间，同时作为分区键。';

COMMENT ON TABLE public.request_logs_default IS 'request_logs 的默认分区，承接尚未命中专用时间分区的调用日志。';
COMMENT ON COLUMN public.request_logs_default.id IS '继承自主表的调用日志记录标识。';
COMMENT ON COLUMN public.request_logs_default.request_id IS '继承自主表的请求标识。';
COMMENT ON COLUMN public.request_logs_default.user_id IS '继承自主表的用户标识。';
COMMENT ON COLUMN public.request_logs_default.api_key_id IS '继承自主表的 API Key 标识。';
COMMENT ON COLUMN public.request_logs_default.model_id IS '继承自主表的平台模型标识。';
COMMENT ON COLUMN public.request_logs_default.channel_id IS '继承自主表的上游渠道标识。';
COMMENT ON COLUMN public.request_logs_default.group_id IS '继承自主表的路由分组标识。';
COMMENT ON COLUMN public.request_logs_default.public_model IS '继承自主表的平台公开模型名。';
COMMENT ON COLUMN public.request_logs_default.upstream_model IS '继承自主表的上游真实模型名。';
COMMENT ON COLUMN public.request_logs_default.started_at IS '继承自主表的请求开始时间。';
COMMENT ON COLUMN public.request_logs_default.completed_at IS '继承自主表的请求完成时间。';
COMMENT ON COLUMN public.request_logs_default.duration_ms IS '继承自主表的请求耗时，单位毫秒。';
COMMENT ON COLUMN public.request_logs_default.status_code IS '继承自主表的 HTTP 状态码。';
COMMENT ON COLUMN public.request_logs_default.platform_error_code IS '继承自主表的平台错误码。';
COMMENT ON COLUMN public.request_logs_default.input_tokens IS '继承自主表的输入 Token 数。';
COMMENT ON COLUMN public.request_logs_default.output_tokens IS '继承自主表的输出 Token 数。';
COMMENT ON COLUMN public.request_logs_default.cached_tokens IS '继承自主表的缓存 Token 数。';
COMMENT ON COLUMN public.request_logs_default.billed_amount IS '继承自主表的最终结算额度。';
COMMENT ON COLUMN public.request_logs_default.price_multiplier IS '继承自主表的价格倍率快照。';
COMMENT ON COLUMN public.request_logs_default.streaming IS '继承自主表的流式响应标记。';
COMMENT ON COLUMN public.request_logs_default.retry_count IS '继承自主表的上游重试次数。';
COMMENT ON COLUMN public.request_logs_default.client_ip IS '继承自主表的客户端来源 IP。';
COMMENT ON COLUMN public.request_logs_default.user_agent_hash IS '继承自主表的 User-Agent 不可逆摘要。';
COMMENT ON COLUMN public.request_logs_default.upstream_error_summary IS '继承自主表的上游错误脱敏摘要。';
COMMENT ON COLUMN public.request_logs_default.route_switch_reason IS '继承自主表的路由切换原因。';
COMMENT ON COLUMN public.request_logs_default.metadata IS '继承自主表的非敏感扩展元数据。';
COMMENT ON COLUMN public.request_logs_default.created_at IS '继承自主表的日志写入时间和分区键。';

COMMENT ON TABLE public.usage_aggregates IS '按时间桶和维度汇总的调用量、Token、费用与延迟统计表。';
COMMENT ON COLUMN public.usage_aggregates.id IS '用量聚合记录自增标识。';
COMMENT ON COLUMN public.usage_aggregates.bucket_start IS '统计时间桶起始时间。';
COMMENT ON COLUMN public.usage_aggregates.bucket_size IS '时间桶粒度：minute、hour 或 day。';
COMMENT ON COLUMN public.usage_aggregates.dimension_type IS '聚合维度类型，例如 user、api_key、model、channel 或 group。';
COMMENT ON COLUMN public.usage_aggregates.dimension_id IS '聚合维度对应的业务标识字符串。';
COMMENT ON COLUMN public.usage_aggregates.request_count IS '时间桶内请求总数。';
COMMENT ON COLUMN public.usage_aggregates.success_count IS '时间桶内成功请求数。';
COMMENT ON COLUMN public.usage_aggregates.input_tokens IS '时间桶内输入 Token 总数。';
COMMENT ON COLUMN public.usage_aggregates.output_tokens IS '时间桶内输出 Token 总数。';
COMMENT ON COLUMN public.usage_aggregates.billed_amount IS '时间桶内最终结算的平台额度总额。';
COMMENT ON COLUMN public.usage_aggregates.latency_sum_ms IS '时间桶内请求耗时总和，单位毫秒，用于计算平均延迟。';
COMMENT ON COLUMN public.usage_aggregates.latency_p95_ms IS '时间桶内请求延迟 P95，单位毫秒。';
COMMENT ON COLUMN public.usage_aggregates.created_at IS '聚合记录创建时间。';
COMMENT ON COLUMN public.usage_aggregates.updated_at IS '聚合记录最后更新时间。';

COMMENT ON TABLE public.notifications IS '面向用户的站内通知和平台公告表。';
COMMENT ON COLUMN public.notifications.id IS '通知全局唯一标识。';
COMMENT ON COLUMN public.notifications.user_id IS '通知接收用户标识；为空时可表示全局公告。';
COMMENT ON COLUMN public.notifications.type IS '通知业务类型，用于前端分类展示。';
COMMENT ON COLUMN public.notifications.title IS '通知标题。';
COMMENT ON COLUMN public.notifications.content IS '通知正文，展示前必须按输出上下文安全转义。';
COMMENT ON COLUMN public.notifications.action_url IS '通知关联的站内操作地址；无跳转时为空。';
COMMENT ON COLUMN public.notifications.read_at IS '用户首次标记已读的时间；未读时为空。';
COMMENT ON COLUMN public.notifications.expires_at IS '通知失效时间；永久保留时为空。';
COMMENT ON COLUMN public.notifications.created_at IS '通知创建时间。';

COMMENT ON TABLE public.health_checks IS '渠道和分组的周期性健康检测结果明细表。';
COMMENT ON COLUMN public.health_checks.id IS '健康检测记录自增标识。';
COMMENT ON COLUMN public.health_checks.target_type IS '检测目标类型：channel 或 group。';
COMMENT ON COLUMN public.health_checks.target_id IS '被检测渠道或分组的业务标识。';
COMMENT ON COLUMN public.health_checks.status IS '检测状态：healthy、degraded、unavailable 或 unconfigured。';
COMMENT ON COLUMN public.health_checks.latency_ms IS '健康检测请求耗时，单位毫秒。';
COMMENT ON COLUMN public.health_checks.error_summary IS '健康检测失败的脱敏错误摘要。';
COMMENT ON COLUMN public.health_checks.checked_at IS '执行本次健康检测的时间。';

COMMENT ON TABLE public.audit_logs IS '关键认证、资金和管理操作审计表，before_data 与 after_data 禁止保存敏感凭证。';
COMMENT ON COLUMN public.audit_logs.id IS '审计记录自增标识。';
COMMENT ON COLUMN public.audit_logs.actor_user_id IS '执行操作的用户标识；系统任务执行时可为空。';
COMMENT ON COLUMN public.audit_logs.actor_type IS '操作主体类型，例如 user、admin 或 system。';
COMMENT ON COLUMN public.audit_logs.action IS '稳定的审计动作代码。';
COMMENT ON COLUMN public.audit_logs.resource_type IS '被操作资源类型。';
COMMENT ON COLUMN public.audit_logs.resource_id IS '被操作资源的业务标识字符串。';
COMMENT ON COLUMN public.audit_logs.before_data IS '操作前的脱敏数据快照 JSON，禁止包含密码、Token、密钥或完整凭证。';
COMMENT ON COLUMN public.audit_logs.after_data IS '操作后的脱敏数据快照 JSON，禁止包含密码、Token、密钥或完整凭证。';
COMMENT ON COLUMN public.audit_logs.ip_address IS '操作来源 IP，用于安全追踪。';
COMMENT ON COLUMN public.audit_logs.user_agent_hash IS '操作来源 User-Agent 的不可逆摘要。';
COMMENT ON COLUMN public.audit_logs.request_id IS '关联 HTTP 请求标识。';
COMMENT ON COLUMN public.audit_logs.created_at IS '审计记录创建时间。';

COMMENT ON TABLE public.outbox_events IS '事务外发事件表，用于在本地事务提交后可靠异步发布消息。';
COMMENT ON COLUMN public.outbox_events.id IS 'Outbox 事件全局唯一标识。';
COMMENT ON COLUMN public.outbox_events.aggregate_type IS '产生事件的聚合类型。';
COMMENT ON COLUMN public.outbox_events.aggregate_id IS '产生事件的聚合业务标识。';
COMMENT ON COLUMN public.outbox_events.event_type IS '稳定的事件类型代码。';
COMMENT ON COLUMN public.outbox_events.payload IS '待发布的事件负载 JSON，禁止包含密码、Token 或完整凭证。';
COMMENT ON COLUMN public.outbox_events.status IS '投递状态：pending、processing、published 或 failed。';
COMMENT ON COLUMN public.outbox_events.attempts IS '事件投递尝试次数。';
COMMENT ON COLUMN public.outbox_events.available_at IS '下一次允许投递该事件的时间，用于退避重试。';
COMMENT ON COLUMN public.outbox_events.published_at IS '事件成功发布到消息系统的时间。';
COMMENT ON COLUMN public.outbox_events.created_at IS 'Outbox 事件创建时间。';
